name: Publish

on: [push]

env:
  AWS_REGION: us-west-2

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Cache commit
        uses: actions/cache@v3
        id: restore-commit
        with:
          path: ./*
          key: ${{ github.sha }}
  Publish:
    runs-on: ubuntu-latest
    needs: ['Prepare']
    steps:
      - uses: actions/cache@v3
        id: restore-commit
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Checkout
        if: steps.restore-commit.outputs.cache-hit != 'true'
        uses: actions/checkout@v3.0.2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: github-tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_CONTEXT: repo
          RELEASE_BRANCHES: "main"
          INITIAL_VERSION: 1.2.0
          WITH_V: true
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.github-tag-action.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}