name: Publish

on: [push]

env:
  AWS_REGION: us-west-2

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Cache commit
        uses: actions/cache@v3
        id: restore-commit
        with:
          path: ./*
          key: ${{ github.sha }}
  Publish:
    runs-on: ubuntu-latest
    needs: ['Prepare']
    steps:
      - uses: actions/cache@v3
        id: restore-commit
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Checkout
        if: steps.restore-commit.outputs.cache-hit != 'true'
        uses: actions/checkout@v3.0.2
      - name: Build new base package version
        run: |
          CURRENT_PACKAGE_VERSION=$(node -pe "require('./package.json').version")
          SEMVER=( ${CURRENT_PACKAGE_VERSION//./ } )
          printf -v BUILD_NUM '%(%s)T' -1
          NEW_PACKAGE_VERSION="${SEMVER[0]}.${SEMVER[1]}.${BUILD_NUM}"
          echo $NEW_PACKAGE_VERSION > version.txt
      - name: Increment package patch version
        id: generate-release-version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          NEW_PACKAGE_VERSION=$(cat version.txt)
          echo $NEW_PACKAGE_VERSION > tag.txt
      - name: Increment package prerelease version
        id: generate-prerelease-version
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        run: |
          NEW_PACKAGE_VERSION="$(cat version.txt)-alpha"
          echo $NEW_PACKAGE_VERSION > tag.txt
      - name: Get tag
        id: get-tag
        run: |
          echo "::set-output name=new-tag::$(cat tag.txt)"
      - name: Push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: github-tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.get-tag.outputs.new-tag }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-tag.outputs.new-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}